SET SERVEROUTPUT ON;


DECLARE
    V_EMP_REC EMPLOYEES%ROWTYPE;
    CONTADOR NUMBER(2) := 0;

BEGIN
    FOR CONTADOR IN (SELECT FIRST_NAME FROM EMPLOYEES) LOOP

        V_EMP_REC := CONTADOR;

    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Total de funcionários: ' || V_EMP_RECORDS.FIRST_NAME);
END;